services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - backend_instance:/app/instance
    expose:
      - "5000"

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  backend_instance:
